root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
env:
  node: true

plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'prettier'
rules:
  '@typescript-eslint/naming-convention':
    - warn
    - selector: objectLiteralProperty
      format: [camelCase, snake_case]
  '@typescript-eslint/semi': warn
  curly: warn
  eqeqeq: warn
  no-empty-pattern: warn
  no-throw-literal: warn
  semi: 'off'
overrides:
  - files: ['*.ts', '*.tsx']
    rules:
      no-undef: 'off'
